### PR TITLE
Populate `safeTxGas` using the provided gas limit (`SafeAppProvider`)	

### PR DESCRIPTION
**Pull request by solimander**
Currently, it is not possible to populate the `safeTxGas` when using a safe app that communicates through the `SafeAppProvider` (e.g. WalletConnect).

This PR updates the Safe App Provider to forward the provided gas limit to `safeTxGas`. This is helpful in many cases where a gas buffer is required to avoid "Out of gas" errors.

### CODE REVIEW

**Comment by solimander** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mikhailxyz** [comment]
Could you please add a changeset?

**Comment by solimander** [comment]
@mikhailxyz Added 👍

**Comment by mikhailxyz** [comment]
@solimander we've discussed this internally and we're ready to accept this pull request if this behaviour gets properly documented. Could you please add something along these lines into `safe-apps-provider` readme?

> ### Note on gas limit
> 
> The ethereum transaction gas limit passed to the `safe-apps-provider` will be treated as `safeTxGas`, which is an equivalent of the ethereum transaction gas limit in the Safe context. To learn more about the safe transaction gas, read here: https://github.com/safe-global/safe-contracts/blob/c36bcab46578a442862d043e12a83fec41143dec/docs/safe_tx_gas.md

**Review by mikhailxyz — APPROVED** [review]

**Pull request merged**
