### PR TITLE
Upgrade wagmi example

### PR DESCRIPTION
**Pull request by brightiron**
Hello frens!

The wagmi version used in the example is out of date, and hooks have changed. This PR updates the example to the latest version of the wagmi library and migrates those hooks

### CODE REVIEW

**Comment by brightiron** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mikhailxyz** [comment]
thanks fren @brightiron , much appreciated. Have you tested it?

**Comment by brightiron** [comment]
> thanks fren @brightiron , much appreciated. Have you tested it?

I was having issues w/ running the example directly inside the repo (not sure if it's lerna related or because there are shared dependencies from the parent project, or what). 

But if i take the example/wagmi dir and run it in its own isolated project (and add the missing typescript dependency), it runs w/o issue.

It may be worthwhile to add an independent yarn.lock file here, or more explicitly add dependencies to the package.json file (i.e. typescript). so that anyone leveraging this example can just copy the example dir to their own project... i just didn't want to clutter this PR with changes unrelated to wagmi itself.  

more of an fyi, we also have an open PR in our dapp here (PR is here: https://github.com/OlympusDAO/olympus-frontend/pull/2164) . 

Cheers!

**Comment by mikhailxyz** [comment]
one thing @brightiron , could you create changeset for your changes? you can do that by executing `npx changeset`

**Comment by mikhailxyz** [comment]
The example app doesn't compile for me:

> Compiled with problems:X
> 
> ERROR in src/index.tsx:29:5
> 
> TS2322: Type 'SafeConnector' is not assignable to type 'Connector<any, any, any>'.
>   Property 'onAccountsChanged' is protected but type 'SafeConnector' is not a class derived from 'Connector<Provider, Options, Signer>'.
>     27 | const client = createClient({
>     28 |   connectors: [
>   > 29 |     new SafeConnector({ chains }),
>        |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     30 |     new MetaMaskConnector({ chains }),
>     31 |     new WalletConnectConnector({
>     32 |       chains,

**Comment by mikhailxyz** [comment]
It looks like to update the example app, you also have to update the wagmi package itself. We currently have no resources but hopefully will get to it soon

**Comment by dasanra** [comment]
Closing. This PR was finished in
https://github.com/safe-global/safe-apps-sdk/pull/370

**Pull request closed without merging**
