### PR TITLE
feat: return signatures when signing message if they are present in the response

### PR DESCRIPTION
**Pull request by schmanu**
Part of https://github.com/safe-global/web-core/issues/1886

## Overview
In order to enable a synchronous EIP-1271 signing flow, we have to return the signatures which are returned from the signing request.
The plan is to wait in the Safe{Wallet} web interface until the message is fully signed and then return the `preparedSignature` from our tx service.

This will make a lot of Dapps work with Safe off-chain signatures.

### CODE REVIEW

**Comment by mmv08** [comment]
Could you please add a changeset and remove the version change? The release process is documented here: 
https://github.com/safe-global/safe-apps-sdk/blob/main/docs/releases.md

You can skip the pre part unless you want to release a beta version first.

**Review by mmv08 — COMMENTED** [review]
LGTM but there's something wrong with the tests. Also don't forget to push the `dist` folder so the package can be used directly from github 👍

**Comment by schmanu** [comment]
> LGTM but there's something wrong with the tests. Also don't forget to push the `dist` folder so the package can be used directly from github 👍

We updated to node 18 which supports window.crypto. The polyfill in the jest setup broke the test.
I removed it and now they run.

**Review by yagopv — APPROVED** [review]

**Comment by yagopv** [comment]
Hey @schmanu i guess you removed the `getRandomValues` because it is now implemented in jsdom right. In any case, please remove it as well [here](https://github.com/gnosis/safe-apps-sdk/blob/17411b3f94243cdaf0ac038a26c1855ec8fb6f01/guides/drain-safe-app/app/src/setupTests.ts#L1-L31) then

**Pull request merged**
